### ISSUE TITLE
Kehitysidea: Värinäkuvio hälyttäessä

### ISSUE THREAD

**Issue by Forret** [Kultalaaki/VPKApuri#1]
Hei,

Ensinnäkin kiitokset loistavasta sovelluksesta.

Olisi hienoa, jos sovelluksella olisi oma värinäkuvio jonka keston voisi määritellä asetuksista. Esim. Sovellus värisee hälytyksen tullessa SOS -kuviolla (kolme lyhyttä, kolme pitkää ja kolme lyhyttä värinää). Värinäkuvio kestäisi niin kauan, kunnes hälytyksen avaa. 

Vanhassa Fire Alert 2 -sovelluksessa oli tämä toiminto ja sitä on moni tuttu jäänyt kaipaamaan. 
Oli varsinkin silloin kätevä, kun kännykkä on äänettömällä ja hälytykset myös. Tällöin pelkästä värinästä pystyi tietämään saapuvasta hälytyksestä.

Mukavaa kesän jatkoa!

**Comment by Kultalaaki** [comment]
Värinäkuviot lisätty ja tulee seuraavan päivityksen mukana.
