### ISSUE TITLE
Sovellus ei reagoi H352-tehtäviin

### ISSUE THREAD

**Issue by peholmst** [Kultalaaki/VPKApuri#3]
Aina kun tulee valmiussiirtotehtävä H352 Korppooseen niin sovellus ei reagoi. Ilmoita jos tarvitset esimerkkiviestin niin voin lähettää privana.

**Comment by Kultalaaki** [comment]
Kiitos ilmoituksesta.

Tämä on tullut jo aikaisemmin ilmi. En ole vielä kerennyt tekemään korjausta ongelmaan. Seuraavan päivityksen yhteydessä korjataan. Päivityksen aikataulusta en tosin osaa vielä kertoa mitään.

**Comment by peholmst** [comment]
Terve! Auttaisiko jos korjaisin itse ja tekisin PR:n?

**Comment by Kultalaaki** [comment]
Tällä hetkellä sovelluksen tuo kohta missä toi virhe on niin se pitää kirjoittaa kokonaan uusiksi. Siellä on taustaservice (IsItAlarmService) missä noi kaikki osoitteentunnistus sekä hälytystunnuksien haku tapahtuu. Se olisi tarkoitus kirjoittaa kokonaan uuteen muotoon. Silloin kun sen tein niin olin sen verran uuno kirjoittaan koodia että siitä tuli niin sanottu spagettikoodi.

Nyt kun enemmän opiskellut ohjelmointia niin tiedän miten sen toteutan uudestaan. 

Tietenkin jos intoa piisaa ja haluaa ilman korvausta auttaa niin ilman muuta. Itsellekkin hyötyä jos saisi 
?kokeneemman? henkilön apuja tai vinkkejä.

**Comment by peholmst** [comment]
Selvä juttu, katson mitä voin tehdä jos ehdin (kesäloma loppui, tänään eka päivä takaisin työssä).
